AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      DefinitionUri: swagger.yaml
      StageName: Prod
      Variables:
        LambdaFunctionName: !Ref lambdaGatewayApi
  lambdaGatewayApi:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      CodeUri: ./src
      Environment:
        Variables:
          S3_BUCKET: jochen-lambda-test
      Events:
        AddPhotoApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /
            Method: get

  # lambda-s3:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     Handler: index.handler
  #     Runtime: nodejs6.10
  #     CodeUri: ./s3
  #     Environment:
  #       Variables:
  #         S3_BUCKET: jochen-lambda-test
